language: ruby
dist: xenial
sudo: false

before_install:
  - script/travis-downgrade-bundler-on-old-rails.sh

script:
  - bundle exec rspec --format d
  - CODECLIMATE_TO_FILE=1 bundle exec codeclimate-test-reporter
  # NB: --groups must equal to the total number of jobs = dbs * gemfiles * rubies.
  - bundle exec codeclimate-batch --groups 18

matrix:
  include:
    - name: Rubocop
      gemfile: spec/gemfiles/rubocop.gemfile
      rvm: 2.5.3
      script: bundle exec rubocop
      before_install:
    - gemfile: spec/gemfiles/rails_4_1.gemfile
      rvm: 2.2.9
      env: DB=sqlite3
    - gemfile: spec/gemfiles/rails_4_1.gemfile
      rvm: 2.2.9
      env: DB=mysql2 DB_USERNAME=root DB_PASSWORD=""
      services: mysql
    - gemfile: spec/gemfiles/rails_4_1.gemfile
      rvm: 2.2.9
      env: DB=postgresql DB_USERNAME=postgres DB_PASSWORD=""
      services: postgresql
    - gemfile: spec/gemfiles/rails_4_2.gemfile
      rvm: 2.3.8
      env: DB=sqlite3
    - gemfile: spec/gemfiles/rails_4_2.gemfile
      rvm: 2.3.8
      env: DB=mysql2 DB_USERNAME=root DB_PASSWORD=""
      services: mysql
    - gemfile: spec/gemfiles/rails_4_2.gemfile
      rvm: 2.3.8
      env: DB=postgresql DB_USERNAME=postgres DB_PASSWORD=""
      services: postgresql
    - gemfile: spec/gemfiles/rails_5_0.gemfile
      rvm: 2.3.8
      env: DB=sqlite3
    - gemfile: spec/gemfiles/rails_5_0.gemfile
      rvm: 2.3.8
      env: DB=mysql2 DB_USERNAME=root DB_PASSWORD=""
      services: mysql
    - gemfile: spec/gemfiles/rails_5_0.gemfile
      rvm: 2.3.8
      env: DB=postgresql DB_USERNAME=postgres DB_PASSWORD=""
      services: postgresql
    - gemfile: spec/gemfiles/rails_5_1.gemfile
      rvm: 2.3.8
      env: DB=sqlite3
    - gemfile: spec/gemfiles/rails_5_1.gemfile
      rvm: 2.3.8
      env: DB=mysql2 DB_USERNAME=root DB_PASSWORD=""
      services: mysql
    - gemfile: spec/gemfiles/rails_5_1.gemfile
      rvm: 2.3.8
      env: DB=postgresql DB_USERNAME=postgres DB_PASSWORD=""
      services: postgresql
    - gemfile: spec/gemfiles/rails_5_2.gemfile
      rvm: 2.3.8
      env: DB=sqlite3
    - gemfile: spec/gemfiles/rails_5_2.gemfile
      rvm: 2.3.8
      env: DB=mysql2 DB_USERNAME=root DB_PASSWORD=""
      services: mysql
    - gemfile: spec/gemfiles/rails_5_2.gemfile
      rvm: 2.3.8
      env: DB=postgresql DB_USERNAME=postgres DB_PASSWORD=""
      services: postgresql
    - gemfile: spec/gemfiles/rails_6_0.gemfile
      rvm: 2.5.3
      env: DB=sqlite3
    - gemfile: spec/gemfiles/rails_6_0.gemfile
      rvm: 2.5.3
      env: DB=mysql2 DB_USERNAME=root DB_PASSWORD=""
      services: mysql
    - gemfile: spec/gemfiles/rails_6_0.gemfile
      rvm: 2.5.3
      env: DB=postgresql DB_USERNAME=postgres DB_PASSWORD=""
      services: postgresql
    - gemfile: spec/gemfiles/rails_6_1.gemfile
      rvm: 3.0.0
      env: DB=postgresql DB_USERNAME=postgres DB_PASSWORD=""
      services: postgresql

cache: bundler
bundler_args: --path ../../vendor/bundle --without debug

env:
  global:
  - COVERAGE=1 TRAVIS=1
